source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :osx, '10.13'
workspace 'eqMac.xcworkspace'
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.13'
      if target.name == 'AMCoreAudio'
        config.build_settings['DEFINES_MODULE'] = 'YES'
      end
    end
  end
end

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
  pod 'STPrivilegedTask', '~> 1.0'
end

project 'app/eqMac.xcodeproj'

target 'eqMac' do
  project 'app/eqMac.xcodeproj'

  pod 'AMCoreAudio', :path => 'Vendor/AMCoreAudio'
  pod 'WebViewJavascriptBridge', :git => 'https://github.com/marcuswestin/WebViewJavascriptBridge.git', :tag => 'v6.0.3'
#  pod 'ReachabilitySwift'
  pod 'ReSwift', :git => 'https://github.com/ReSwift/ReSwift.git', :tag => '6.1.0'
  pod 'SwiftLint'
  pod 'Sparkle', '~> 1.24'
  pod 'EmitterKit', :git => 'https://github.com/aleclarson/emitter-kit.git', :tag => '5.2.2'
  pod 'SwiftyJSON', '~> 4.2'
  pod 'SwiftyUserDefaults', '4.0'
  pod 'KeychainSwift', '~> 13.0'
  pod 'Zip', '~> 2.1'
  shared_pods

end
