source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'
workspace 'eqMac.xcworkspace'
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.12'
    end
  end

  sentry_cpp_exception = File.join(installer.sandbox.root, 'Sentry', 'Sources', 'SentryCrash', 'Recording', 'Monitors', 'SentryCrashMonitor_CPPException.cpp')
  if File.exist?(sentry_cpp_exception)
    contents = File.read(sentry_cpp_exception)
    unless contents.include?('#include <exception>')
      contents.sub!('#include <dlfcn.h>', "#include <dlfcn.h>\n#include <exception>")
      File.write(sentry_cpp_exception, contents)
    end
  end

  sentry_machine_context = File.join(installer.sandbox.root, 'Sentry', 'Sources', 'SentryCrash', 'Recording', 'Tools', 'SentryCrashMachineContext.c')
  if File.exist?(sentry_machine_context)
    contents = File.read(sentry_machine_context)
    unless contents.include?('#include <sys/_types/_ucontext64.h>')
      contents.sub!('#include <mach/mach.h>', "#include <mach/mach.h>\n#include <sys/_types/_ucontext64.h>")
      File.write(sentry_machine_context, contents)
    end
  end

  amcoreaudio_source = File.join(installer.sandbox.root, 'AMCoreAudio', 'Source')
  Dir.glob(File.join(amcoreaudio_source, '**', '*.swift')).each do |swift_file|
    contents = File.read(swift_file)
    updated = contents
      .gsub('import CoreAudio.AudioHardwareBase', 'import CoreAudio')
      .gsub('kAudioHardwareServiceDeviceProperty_VirtualMasterVolume', 'kAudioHardwareServiceDeviceProperty_VirtualMainVolume')
      .gsub('kAudioHardwareServiceDeviceProperty_VirtualMasterBalance', 'kAudioHardwareServiceDeviceProperty_VirtualMainBalance')
    File.write(swift_file, updated) if updated != contents
  end
end

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
  pod 'STPrivilegedTask', :git => 'https://github.com/sveinbjornt/STPrivilegedTask.git', :commit => 'fdca677c77adb166a2be4c5ea9c7580a738c49c9'
end

project 'app/eqMac.xcodeproj'

target 'eqMac' do
  project 'app/eqMac.xcodeproj'

  pod 'SwiftHTTP', '~> 3.0'
  pod 'AMCoreAudio', :podspec => 'AMCoreAudio-fixed.podspec'
  pod 'WebViewJavascriptBridge', '~> 6.0'
#  pod 'ReachabilitySwift'
  pod 'ReSwift', '~> 6.1'
  pod 'SwiftLint'
  pod 'Sparkle', '~> 1.24'
  pod 'Sentry', '~> 7.1.3'
  pod 'EmitterKit', '~> 5.2.2'
  pod 'SwiftyJSON', '~> 4.2'
  pod 'SwiftyUserDefaults', '4.0'
  pod 'KeychainSwift', '~> 13.0'
  pod 'Zip', :git => 'https://github.com/bitgapp/Zip.git'
  shared_pods

end
